name = "voxel-canvas"
main = "src/index.ts"
compatibility_date = "2024-10-01"

[durable_objects]
bindings = [
  { name = "VOXEL_ROOM", class_name = "VoxelRoomDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["VoxelRoomDO"]

[vars]
ROOM_SEED_SECRET = "dev-seed-ok"